"""add created_at to users_alembic

Revision ID: 63deff645a81
Revises: 751fbdfe49d9
Create Date: 2026-01-23 17:51:20.776338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63deff645a81'
down_revision: Union[str, Sequence[str], None] = '751fbdfe49d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_alembic', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_alembic', 'created_at')
    # ### end Alembic commands ###
